apiVersion: apps/v1
kind: Deployment
metadata:
  name: wt-pod
  namespace: wt-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wt
  template:
    metadata:
      labels:
        app: wt
    spec:
      containers:
        # sales-api container configuration
        - name: wt-api
          resources:
            limits:
              cpu: "2000m" # Up to 2 full cores
            requests:
              cpu: "1000m" # Use 1 full cores