apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/wt-pod
patchesStrategicMerge:
- ./kind-service-patch.yaml
images:
- name: wt-api-image
  newName: wt-api-amd64
  newTag: "1.0"
